#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/../.." && pwd)"
cd "${repo_root}"

dist_config="dist-workspace.toml"
dry_run_workflow=".github/workflows/dist-dry-run-release.yml"

configured_dist_version() {
  sed -n 's/^[[:space:]]*cargo-dist-version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "${dist_config}" | head -n1
}

dist_version_matches() {
  local expected="$1"
  local actual

  actual="$(dist --version 2>/dev/null || true)"
  [ "${actual}" = "cargo-dist ${expected}" ]
}

ensure_dist() {
  local expected

  expected="$(configured_dist_version)"
  if [ -z "${expected}" ]; then
    echo "Could not read cargo-dist-version from ${dist_config}" >&2
    exit 1
  fi

  if command -v dist >/dev/null 2>&1 && dist_version_matches "${expected}"; then
    return
  fi

  echo "Installing cargo-dist ${expected}..."
  curl --proto '=https' --tlsv1.2 -LsSf \
    "https://github.com/axodotdev/cargo-dist/releases/download/v${expected}/cargo-dist-installer.sh" |
    sh
  export PATH="${HOME}/.cargo/bin:${PATH}"

  if ! command -v dist >/dev/null 2>&1 || ! dist_version_matches "${expected}"; then
    echo "cargo-dist ${expected} was not available after installation" >&2
    exit 1
  fi
}

write_dry_run_dist_config() {
  local source_config="$1"

  awk '
    BEGIN {
      in_dist = 0
      inserted = 0
    }

    function insert_settings() {
      if (!inserted) {
        print "dispatch-releases = true"
        print "pr-run-mode = \"skip\""
        print "tag-namespace = \"dist-dry-run\""
        inserted = 1
      }
    }

    /^\[dist\]$/ {
      in_dist = 1
      print
      next
    }

    /^\[/ && in_dist {
      insert_settings()
      in_dist = 0
    }

    in_dist && /^(dispatch-releases|pr-run-mode|tag-namespace)[[:space:]]*=/ {
      next
    }

    { print }

    END {
      if (in_dist) {
        insert_settings()
      }
    }
  ' "${source_config}" > "${dist_config}"
}

apply_dry_run_safety_overlay() {
  perl -0pi -e '
    s/\A(# This file was autogenerated[^\n]*\n)#\n/$1# It was generated with temporary dry-run settings:\n# dispatch-releases = true, pr-run-mode = "skip", tag-namespace = "dist-dry-run".\n# The workflow name, permissions, and non-dry-run input guard are deterministic safety edits applied by .github\/scripts\/regen-dist-release.sh.\n#\n/s;
    s/^name: Release$/name: cargo-dist Dry Run/m;
    s/"contents": "write"/"contents": "read"/;
    s/description: Release Tag/description: Dry-run sentinel. Leave as dry-run; real tags are refused./;
    s/(\n      - uses: actions\/checkout\@v6\n        with:\n          persist-credentials: false\n          submodules: recursive\n)(      - name: Install dist\n)/$1      - name: Refuse real release tags\n        if: \${{ inputs.tag != '\''dry-run'\'' }}\n        run: |\n          echo "::error::This workflow is only for cargo-dist dry runs. Leave the tag input set to dry-run."\n          exit 1\n$2/s;
  ' "${dry_run_workflow}"
}

ensure_dist

echo "Regenerating .github/workflows/release.yml..."
dist generate --mode=ci

tmpdir="$(mktemp -d)"
cleanup() {
  local status="$?"

  if [ -f "${tmpdir}/${dist_config}" ]; then
    cp "${tmpdir}/${dist_config}" "${dist_config}"
  fi
  rm -rf "${tmpdir}"
  exit "${status}"
}
trap cleanup EXIT

cp "${dist_config}" "${tmpdir}/${dist_config}"
write_dry_run_dist_config "${tmpdir}/${dist_config}"

echo "Regenerating ${dry_run_workflow} with temporary dry-run settings..."
dist generate --mode=ci

cp "${tmpdir}/${dist_config}" "${dist_config}"
trap - EXIT
rm -rf "${tmpdir}"

apply_dry_run_safety_overlay
